name = "brutal"
description = "A simple (brutal), but elegant light theme"
license = "MIT"
homepage = "https://github.com/maxild/zola-brutal-theme"
min_version = "0.11.0"
demo = "https://maxild.github.io"

[extra]
even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/about", name = "About"},
]
even_title = "Even"

# I will not  change this until something new is created...
[author]
name = "Vincent Prouillet"
homepage = "https://www.vincentprouillet.com"

[original]
author =  "olOwOlo"
homepage = "https://blog.olowolo.com/example-site/"
repo = "https://github.com/olOwOlo/hugo-theme-even"
